# Change these first
owner: kt-chelsea # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Chelsea
    url: http://chelsea.kt.co.kr
  - name: KTDN
    url: http://ktdn.chelsea.kt.co.kr
  - name: Gitlab
    url: http://scm.chelsea.kt.co.kr
  - name: Orchestra
    url: http://issue.chelsea.kt.co.kr
  - name: Nexus
    url: http://repo.chelsea.kt.co.kr
  - name: Jenkins
    url: http://build.chelsea.kt.co.kr
  - name: Ansible
    url: http://deploy.chelsea.kt.co.kr/#/login
  - name: MatterMost
    url: http://chat.chelsea.kt.co.kr/login
  - name: Xwiki
    url: http://wiki.chelsea.kt.co.kr/xwiki/bin/view/Main/
  - name: SonarQube
    url: http://codeanlys.chelsea.kt.co.kr/sessions/new?return_to=%2F
  - name: Reviewboard
    url: http://codeanlys.chelsea.kt.co.kr/sessions/new?return_to=%2F
    
notifications:
  - type: slack
    channel: C01DEA0PK0E

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 첼시 사이트 상태
  introTitle: "**Upptime** for Chelsea"
  introMessage: 첼시에서 운영되는 사이트들의 현재 상태입니다. Gitub의 Action을 사용하고, Upptime의 오픈소스를 사용하였습니다.
  navbar:
    - title: Status
      href: /
    - title: Chelsea
      href: http://chelsea.kt.co.kr
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
